---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ controller_configs_dir | default((lookup('env', 'CONTROLLER_CONFIGS_DIR') == '') | ternary('./configs', lookup('env', 'CONTROLLER_CONFIGS_DIR'))) }}"
        ignore_files: ["{{ controller_ignore_files }}"]
        extensions: ["{{ controller_file_target }}"]
      tags:
        - always

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
